from pydantic import BaseModel

class ProductBase(BaseModel):
    name: str          # Medicine name
    description: str   # Short description
    price: float       # Price in INR
    category: str      
    diagnosis: str     
    image_url: str     # URL of medicine image
    is_featured: bool = False  # Featured on homepage?

class ProductCreate(ProductBase):
    pass  

class Product(ProductBase):
    id: int  # Auto-generated by Supabase
    
    class Config:
        orm_mode = True  